#!/bin/bash

usage(){
	echo -e "USAGE: \n\t# $0 [-p PORT]"
}

MYPID=$$
mkdir /tmp/thin-${MYPID} 1>&2 2> /dev/null

if [ "$1" == "-p" ] ; then
	PORT="$2"
else
	PORT=3000
fi

echo -e "# The static content rooted in the current working directory\n# Dir.pwd =&gt;http://0.0.0.0:$PORT/\n#\nroot=Dir.pwd\nputs \">>> Serving: #{root}\"\nrun Rack::Directory.new(\"#{root}\")" > /tmp/thin-${MYPID}/static.ru

thin -R /tmp/thin-${MYPID}/static.ru start -p $PORT

rm -Rf /tmp/thin-${MYPID}
