#!/bin/bash

mkdir /tmp/thin 1>&2 2> /dev/null

echo -e "# The static content rooted in the current working directory\n# Dir.pwd =&gt;http://0.0.0.0:3000/\n#\nroot=Dir.pwd\nputs \">>> Serving: #{root}\"\nrun Rack::Directory.new(\"#{root}\")" > /tmp/thin/static.ru

thin -R /tmp/thin/static.ru start

rm -Rf /tmp/thin
